-- Retrieve all data from Patient table
SELECT * FROM Patient;

-- Retrieve all data from Doctor table
SELECT * FROM Doctor;

-- Retrieve all data from Treatment table
SELECT * FROM Treatment;

-- Retrieve all data from Appointment table
SELECT * FROM Appointment;

-- Retrieve all data from Visit table
SELECT * FROM Visit;

-- Retrieve all data from Visit_Treatment table
SELECT * FROM Visit_Treatment;

-- Retrieve all data from Invoice table
SELECT * FROM Invoice;

-- Retrieve all data from Payment table
SELECT * FROM Payment;

-- Retrieve all data from SystemUser table
    SELECT * FROM SystemUser;

SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME = 'SystemUser';

-- Display all appointments with patient and doctor name
SELECT 
    CONCAT(p.First_Name, ' ', p.Last_Name) AS Patient_Name,
    d.Name AS Doctor_Name,
    a.AppointmentDate,
    a.Appointment_Time,
    a.Status
FROM Appointment a
JOIN Patient p ON a.Patient_ID = p.Patient_ID
JOIN Doctor d ON a.Doctor_ID = d.Doctor_ID
ORDER BY a.AppointmentDate;

-- Number of appointments per doctor 
SELECT 
    d.Name AS Doctor_Name,
    COUNT(a.Appointment_ID) AS Total_Appointments
FROM Doctor d
LEFT JOIN Appointment a ON d.Doctor_ID = a.Doctor_ID
GROUP BY d.Name;

-- Total earnings per doctor
SELECT 
    d.Name AS Doctor_Name,
    SUM(i.Final_Amount) AS Total_Revenue
FROM Doctor d
JOIN Appointment a ON d.Doctor_ID = a.Doctor_ID
JOIN Visit v ON a.Appointment_ID = v.Appointment_ID
JOIN Invoice i ON v.Visit_ID = i.Visit_ID
GROUP BY d.Name;

-- Patients who owe money (Unpaid / Partial)
SELECT 
    CONCAT(p.First_Name, ' ', p.Last_Name) AS Patient_Name,
    i.Final_Amount,
    i.Status
FROM Patient p
JOIN Appointment a ON p.Patient_ID = a.Patient_ID
JOIN Visit v ON a.Appointment_ID = v.Appointment_ID
JOIN Invoice i ON v.Visit_ID = i.Visit_ID
WHERE i.Status IN ('Unpaid', 'Partial');



-- What is the total revenue generated by each doctor?
SELECT 
    d.Name AS Doctor_Name,
    SUM(i.Final_Amount) AS Total_Revenue
FROM Doctor d
JOIN Appointment a ON d.Doctor_ID = a.Doctor_ID
JOIN Visit v ON a.Appointment_ID = v.Appointment_ID
JOIN Invoice i ON v.Visit_ID = i.Visit_ID
GROUP BY d.Name;


-- Which patients have unpaid or partially paid invoices?
SELECT 
    CONCAT(p.First_Name, ' ', p.Last_Name) AS Patient_Name,
    i.Final_Amount,
    i.Status
FROM Patient p
JOIN Appointment a ON p.Patient_ID = a.Patient_ID
JOIN Visit v ON a.Appointment_ID = v.Appointment_ID
JOIN Invoice i ON v.Visit_ID = i.Visit_ID
WHERE i.Status IN ('Unpaid', 'Partial');


-- What is the most frequently used treatment?
SELECT 
    t.Treatment_Name,
    SUM(vt.Quantity) AS Usage_Count
FROM Treatment t
JOIN Visit_Treatment vt ON t.Treatment_ID = vt.Treatment_ID
GROUP BY t.Treatment_Name
ORDER BY Usage_Count DESC;


-- What is the total amount paid for each invoice?
SELECT 
    i.Invoice_ID,
    i.Final_Amount,
    SUM(p.Amount) AS Paid_Amount
FROM Invoice i
LEFT JOIN Payment p ON i.Invoice_ID = p.Invoice_ID
GROUP BY i.Invoice_ID, i.Final_Amount;


-- How many patients are there in each city?
SELECT 
    CAST(Address AS VARCHAR(255)) AS Address,
    COUNT(*) AS Total_Patients
FROM Patient
GROUP BY CAST(Address AS VARCHAR(255));